name: release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            artifact_name: aepcli-linux-amd64
          - os: darwin
            arch: amd64
            artifact_name: aepcli-darwin-amd64
          - os: darwin
            arch: arm64
            artifact_name: aepcli-darwin-arm64
          - os: windows
            arch: amd64
            artifact_name: aepcli-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o ${{ matrix.artifact_name }} ./cmd/aepcli

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
